// This file is auto-generated by scripts/generate-mcp-schemas.ts
// DO NOT EDIT MANUALLY - changes will be overwritten

export interface ComponentSchema {
  name: string
  tagName: string
  description: string
  category: 'form' | 'container' | 'navigation' | 'utility'
  props: PropSchema[]
  slots?: SlotSchema[]
  events?: EventSchema[]
  examples: string[]
}

export interface PropSchema {
  name: string
  type: string
  required: boolean
  default?: any
  description: string
  options?: string[]
}

export interface SlotSchema {
  name?: string
  description: string
}

export interface EventSchema {
  name: string
  description: string
  detail?: string
}

export const componentSchemas: ComponentSchema[] = [
  {
    "name": "base-card",
    "tagName": "base-card",
    "description": "Container card component with variants and expandable support",
    "category": "container",
    "props": [
      {
        "name": "variant",
        "type": "string",
        "required": false,
        "default": "default",
        "description": "Visual style variant",
        "options": [
          "default",
          "elevated"
        ]
      },
      {
        "name": "padding",
        "type": "string",
        "required": false,
        "default": "none",
        "description": "Internal padding size",
        "options": [
          "auto",
          "none",
          "sm",
          "md",
          "lg"
        ]
      },
      {
        "name": "hoverable",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "Show hover effects"
      },
      {
        "name": "expandable",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "Allow expansion to fullscreen"
      }
    ],
    "slots": [
      {
        "description": "Card content"
      }
    ],
    "events": [
      {
        "name": "card-expanded",
        "description": "Fired when card is expanded"
      },
      {
        "name": "card-collapsed",
        "description": "Fired when expanded card is collapsed"
      }
    ],
    "examples": [
      "<base-card variant=\"elevated\" padding=\"md\"><h2>Card Title</h2><p>Card content</p></base-card>",
      "<base-card expandable=\"true\" padding=\"lg\">Click expand icon to view fullscreen</base-card>"
    ]
  },
  {
    "name": "base-drawer",
    "tagName": "base-drawer",
    "description": "Bottom slide-out drawer with iOS-like behavior and drag support",
    "category": "container",
    "props": [
      {
        "name": "open",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "Whether component is open"
      },
      {
        "name": "size",
        "type": "string",
        "required": false,
        "default": "sm",
        "description": "Size of the component",
        "options": [
          "xs",
          "sm",
          "md",
          "lg",
          "full"
        ]
      },
      {
        "name": "persist-on-overlay-click",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "persistOnOverlayClick property"
      },
      {
        "name": "default-detent",
        "type": "string",
        "required": false,
        "default": "",
        "description": "defaultDetent property"
      }
    ],
    "events": [
      {
        "name": "drawer-open",
        "description": "Fired when drawer opens"
      },
      {
        "name": "drawer-close",
        "description": "Fired when drawer closes"
      }
    ],
    "examples": [
      "<base-drawer open=\"true\" detents=\"300px,80%\"><div>Drawer content</div></base-drawer>"
    ]
  },
  {
    "name": "base-list",
    "tagName": "base-list",
    "description": "List container component",
    "category": "container",
    "props": [
      {
        "name": "size",
        "type": "string",
        "required": false,
        "default": "md",
        "description": "Size of the component",
        "options": [
          "xs",
          "sm",
          "md",
          "lg"
        ]
      },
      {
        "name": "variant",
        "type": "string",
        "required": false,
        "default": "default",
        "description": "Visual style variant",
        "options": [
          "default",
          "bordered",
          "divided"
        ]
      },
      {
        "name": "interactive",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "interactive property"
      },
      {
        "name": "role",
        "type": "string",
        "required": false,
        "default": "list",
        "description": "role property"
      },
      {
        "name": "pull-action-icon",
        "type": "string",
        "required": false,
        "description": "pullActionIcon property"
      }
    ],
    "slots": [
      {
        "description": "base-list-item components"
      }
    ],
    "examples": [
      "<base-list><base-list-item>Item 1</base-list-item><base-list-item>Item 2</base-list-item></base-list>"
    ]
  },
  {
    "name": "base-list-item",
    "tagName": "base-list-item",
    "description": "List item with swipe actions for mobile",
    "category": "container",
    "props": [
      {
        "name": "size",
        "type": "string",
        "required": false,
        "default": "md",
        "description": "Size of the component",
        "options": [
          "xs",
          "sm",
          "md",
          "lg"
        ]
      },
      {
        "name": "disabled",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "Whether the component is disabled"
      },
      {
        "name": "selected",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "selected property"
      },
      {
        "name": "interactive",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "interactive property"
      },
      {
        "name": "no-hover",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "noHover property"
      },
      {
        "name": "role",
        "type": "string",
        "required": false,
        "default": "listitem",
        "description": "role property"
      },
      {
        "name": "left-swipe-action",
        "type": "object",
        "required": false,
        "description": "leftSwipeAction property"
      },
      {
        "name": "right-swipe-action",
        "type": "object",
        "required": false,
        "description": "rightSwipeAction property"
      }
    ],
    "slots": [
      {
        "description": "List item content"
      },
      {
        "name": "actions",
        "description": "Swipe action buttons"
      }
    ],
    "examples": [
      "<base-list-item>Item content<div slot=\"actions\"><button>Delete</button></div></base-list-item>"
    ]
  },
  {
    "name": "auth-form",
    "tagName": "auth-form",
    "description": "Authentication form component with login/signup modes",
    "category": "form",
    "props": [
      {
        "name": "initial-mode",
        "type": "string",
        "required": false,
        "default": "signin",
        "description": "initialMode property",
        "options": [
          "signin",
          "signup"
        ]
      },
      {
        "name": "logo-url",
        "type": "string",
        "required": false,
        "default": "",
        "description": "logoUrl property"
      },
      {
        "name": "oauth-domain",
        "type": "string",
        "required": false,
        "default": "",
        "description": "oauthDomain property"
      },
      {
        "name": "oauth-region",
        "type": "string",
        "required": false,
        "default": "",
        "description": "oauthRegion property"
      },
      {
        "name": "oauth-user-pool-id",
        "type": "string",
        "required": false,
        "default": "",
        "description": "oauthUserPoolId property"
      },
      {
        "name": "oauth-client-id",
        "type": "string",
        "required": false,
        "default": "",
        "description": "oauthClientId property"
      },
      {
        "name": "oauth-redirect-uri",
        "type": "string",
        "required": false,
        "default": "",
        "description": "oauthRedirectUri property"
      },
      {
        "name": "oauth-spa-domain",
        "type": "string",
        "required": false,
        "default": "",
        "description": "oauthSpaDomain property"
      },
      {
        "name": "disable-signup",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "disableSignup property"
      },
      {
        "name": "mock-mode",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "mockMode property"
      }
    ],
    "examples": [
      "<auth-form mode=\"login\"></auth-form>",
      "<auth-form mode=\"signup\"></auth-form>"
    ]
  },
  {
    "name": "base-button",
    "tagName": "base-button",
    "description": "Versatile button component with multiple variants and sizes",
    "category": "form",
    "props": [
      {
        "name": "size",
        "type": "string",
        "required": false,
        "default": "md",
        "description": "Size of the component",
        "options": [
          "xs",
          "sm",
          "md",
          "lg"
        ]
      },
      {
        "name": "variant",
        "type": "string",
        "required": false,
        "default": "primary",
        "description": "Visual style variant",
        "options": []
      },
      {
        "name": "hover",
        "type": "string",
        "required": true,
        "description": "Hover state variant"
      },
      {
        "name": "disabled",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "Whether the component is disabled"
      },
      {
        "name": "full-width",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "fullWidth property"
      },
      {
        "name": "loading",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "Show loading state"
      },
      {
        "name": "type",
        "type": "string",
        "required": false,
        "default": "button",
        "description": "Component type",
        "options": [
          "button",
          "submit",
          "reset"
        ]
      }
    ],
    "slots": [
      {
        "description": "Button text content"
      },
      {
        "name": "loading",
        "description": "Custom loading indicator"
      }
    ],
    "examples": [
      "<base-button variant=\"solid-primary\">Click me</base-button>",
      "<base-button variant=\"outlined-danger\" size=\"sm\">Delete</base-button>",
      "<base-button variant=\"ghost-primary\" loading=\"true\">Loading...</base-button>"
    ]
  },
  {
    "name": "base-date-picker",
    "tagName": "base-date-picker",
    "description": "Date selection input",
    "category": "form",
    "props": [
      {
        "name": "value",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Component value"
      },
      {
        "name": "label",
        "type": "string",
        "required": false,
        "description": "Label text displayed"
      },
      {
        "name": "placeholder",
        "type": "string",
        "required": false,
        "default": "Select a date",
        "description": "Placeholder text"
      },
      {
        "name": "required",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "Whether the field is required"
      },
      {
        "name": "disabled",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "Whether the component is disabled"
      },
      {
        "name": "error",
        "type": "string",
        "required": false,
        "description": "Error message to display"
      },
      {
        "name": "hint",
        "type": "string",
        "required": false,
        "description": "Help text displayed"
      },
      {
        "name": "size",
        "type": "string",
        "required": false,
        "default": "md",
        "description": "Size of the component",
        "options": [
          "xs",
          "sm",
          "md",
          "lg"
        ]
      },
      {
        "name": "minDate",
        "type": "string",
        "required": false,
        "description": "minDate property"
      },
      {
        "name": "maxDate",
        "type": "string",
        "required": false,
        "description": "maxDate property"
      }
    ],
    "examples": [
      "<base-date-picker label=\"Birth Date\" required=\"true\"></base-date-picker>"
    ]
  },
  {
    "name": "base-datetime-picker",
    "tagName": "base-datetime-picker",
    "description": "Combined date and time selection",
    "category": "form",
    "props": [
      {
        "name": "value",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Component value"
      },
      {
        "name": "label",
        "type": "string",
        "required": false,
        "description": "Label text displayed"
      },
      {
        "name": "placeholder",
        "type": "string",
        "required": false,
        "default": "Select date and time",
        "description": "Placeholder text"
      },
      {
        "name": "required",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "Whether the field is required"
      },
      {
        "name": "disabled",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "Whether the component is disabled"
      },
      {
        "name": "error",
        "type": "string",
        "required": false,
        "description": "Error message to display"
      },
      {
        "name": "hint",
        "type": "string",
        "required": false,
        "description": "Help text displayed"
      },
      {
        "name": "size",
        "type": "string",
        "required": false,
        "default": "md",
        "description": "Size of the component",
        "options": [
          "xs",
          "sm",
          "md",
          "lg"
        ]
      },
      {
        "name": "minDate",
        "type": "string",
        "required": false,
        "description": "minDate property"
      },
      {
        "name": "maxDate",
        "type": "string",
        "required": false,
        "description": "maxDate property"
      },
      {
        "name": "format",
        "type": "string",
        "required": false,
        "default": "12",
        "description": "format property",
        "options": [
          "12",
          "24"
        ]
      }
    ],
    "examples": [
      "<base-datetime-picker label=\"Event Start Time\"></base-datetime-picker>"
    ]
  },
  {
    "name": "base-input",
    "tagName": "base-input",
    "description": "Text input field with validation and label support",
    "category": "form",
    "props": [
      {
        "name": "value",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Component value"
      },
      {
        "name": "label",
        "type": "string",
        "required": false,
        "description": "Label text displayed"
      },
      {
        "name": "placeholder",
        "type": "string",
        "required": false,
        "description": "Placeholder text"
      },
      {
        "name": "type",
        "type": "string",
        "required": false,
        "default": "text",
        "description": "Component type",
        "options": [
          "text",
          "email",
          "password",
          "tel",
          "url"
        ]
      },
      {
        "name": "required",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "Whether the field is required"
      },
      {
        "name": "disabled",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "Whether the component is disabled"
      },
      {
        "name": "error",
        "type": "string",
        "required": false,
        "description": "Error message to display"
      },
      {
        "name": "hint",
        "type": "string",
        "required": false,
        "description": "Help text displayed"
      },
      {
        "name": "autocomplete",
        "type": "string",
        "required": false,
        "description": "HTML autocomplete attribute"
      },
      {
        "name": "size",
        "type": "string",
        "required": false,
        "default": "md",
        "description": "Size of the component",
        "options": [
          "xs",
          "sm",
          "md",
          "lg"
        ]
      }
    ],
    "slots": [
      {
        "name": "suffix",
        "description": "Content displayed at the end of the input"
      }
    ],
    "events": [
      {
        "name": "input",
        "description": "Fired when input value changes",
        "detail": "{ value: string }"
      },
      {
        "name": "focus",
        "description": "Fired when input receives focus"
      },
      {
        "name": "blur",
        "description": "Fired when input loses focus"
      }
    ],
    "examples": [
      "<base-input label=\"Email\" type=\"email\" placeholder=\"you@example.com\"></base-input>",
      "<base-input label=\"Password\" type=\"password\" required=\"true\"></base-input>",
      "<base-input label=\"Phone\" type=\"tel\" hint=\"Include country code\"></base-input>"
    ]
  },
  {
    "name": "base-select",
    "tagName": "base-select",
    "description": "Dropdown select component with search and multi-select support",
    "category": "form",
    "props": [
      {
        "name": "multiple",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "Allow multiple selections"
      },
      {
        "name": "label",
        "type": "string",
        "required": false,
        "description": "Label text displayed"
      },
      {
        "name": "placeholder",
        "type": "string",
        "required": false,
        "default": "Select an option",
        "description": "Placeholder text"
      },
      {
        "name": "required",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "Whether the field is required"
      },
      {
        "name": "disabled",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "Whether the component is disabled"
      },
      {
        "name": "searchable",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "Enable search functionality"
      },
      {
        "name": "creatable",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "Allow creating new options"
      },
      {
        "name": "error",
        "type": "string",
        "required": false,
        "description": "Error message to display"
      },
      {
        "name": "hint",
        "type": "string",
        "required": false,
        "description": "Help text displayed"
      },
      {
        "name": "size",
        "type": "string",
        "required": false,
        "default": "md",
        "description": "Size of the component",
        "options": [
          "xs",
          "sm",
          "md",
          "lg"
        ]
      },
      {
        "name": "options",
        "type": "array",
        "required": true,
        "description": "options property"
      }
    ],
    "examples": [
      "<base-select label=\"Country\" placeholder=\"Choose country\"></base-select>",
      "<base-select label=\"Tags\" multiple=\"true\" searchable=\"true\" creatable=\"true\"></base-select>"
    ]
  },
  {
    "name": "base-textarea",
    "tagName": "base-textarea",
    "description": "Multi-line text input component",
    "category": "form",
    "props": [
      {
        "name": "value",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Component value"
      },
      {
        "name": "label",
        "type": "string",
        "required": false,
        "description": "Label text displayed"
      },
      {
        "name": "placeholder",
        "type": "string",
        "required": false,
        "description": "Placeholder text"
      },
      {
        "name": "required",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "Whether the field is required"
      },
      {
        "name": "disabled",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "Whether the component is disabled"
      },
      {
        "name": "error",
        "type": "string",
        "required": false,
        "description": "Error message to display"
      },
      {
        "name": "hint",
        "type": "string",
        "required": false,
        "description": "Help text displayed"
      },
      {
        "name": "size",
        "type": "string",
        "required": false,
        "default": "md",
        "description": "Size of the component",
        "options": [
          "xs",
          "sm",
          "md",
          "lg"
        ]
      },
      {
        "name": "rows",
        "type": "number",
        "required": false,
        "default": 4,
        "description": "Number of visible rows"
      },
      {
        "name": "maxlength",
        "type": "number",
        "required": false,
        "description": "maxlength property"
      },
      {
        "name": "resize",
        "type": "string",
        "required": false,
        "default": "vertical",
        "description": "resize property",
        "options": [
          "none",
          "both",
          "horizontal",
          "vertical"
        ]
      }
    ],
    "examples": [
      "<base-textarea label=\"Message\" placeholder=\"Enter your message...\" rows=\"5\"></base-textarea>"
    ]
  },
  {
    "name": "base-time-picker",
    "tagName": "base-time-picker",
    "description": "Time selection input",
    "category": "form",
    "props": [
      {
        "name": "value",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Component value"
      },
      {
        "name": "label",
        "type": "string",
        "required": false,
        "description": "Label text displayed"
      },
      {
        "name": "placeholder",
        "type": "string",
        "required": false,
        "default": "Select a time",
        "description": "Placeholder text"
      },
      {
        "name": "required",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "Whether the field is required"
      },
      {
        "name": "disabled",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "Whether the component is disabled"
      },
      {
        "name": "error",
        "type": "string",
        "required": false,
        "description": "Error message to display"
      },
      {
        "name": "hint",
        "type": "string",
        "required": false,
        "description": "Help text displayed"
      },
      {
        "name": "size",
        "type": "string",
        "required": false,
        "default": "md",
        "description": "Size of the component",
        "options": [
          "xs",
          "sm",
          "md",
          "lg"
        ]
      },
      {
        "name": "format",
        "type": "string",
        "required": false,
        "default": "12",
        "description": "format property",
        "options": [
          "12",
          "24"
        ]
      }
    ],
    "examples": [
      "<base-time-picker label=\"Appointment Time\"></base-time-picker>"
    ]
  },
  {
    "name": "quantity-select",
    "tagName": "quantity-select",
    "description": "Numeric input with increment/decrement controls",
    "category": "form",
    "props": [
      {
        "name": "value",
        "type": "number",
        "required": false,
        "default": 0,
        "description": "Component value"
      },
      {
        "name": "min",
        "type": "number",
        "required": false,
        "default": 0,
        "description": "Minimum value"
      },
      {
        "name": "max",
        "type": "number",
        "required": false,
        "default": 99,
        "description": "Maximum value"
      },
      {
        "name": "size",
        "type": "string",
        "required": false,
        "default": "md",
        "description": "Size of the component",
        "options": [
          "xs",
          "sm",
          "md",
          "lg"
        ]
      },
      {
        "name": "allow-input",
        "type": "boolean",
        "required": false,
        "default": true,
        "description": "allowInput property"
      }
    ],
    "examples": [
      "<quantity-select value=\"1\" min=\"0\" max=\"10\"></quantity-select>"
    ]
  },
  {
    "name": "base-tab",
    "tagName": "base-tab",
    "description": "Individual tab component (must be child of base-tabs)",
    "category": "navigation",
    "props": [
      {
        "name": "id",
        "type": "string",
        "required": false,
        "default": "",
        "description": "id property"
      },
      {
        "name": "label",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Label text displayed"
      },
      {
        "name": "badge",
        "type": "number",
        "required": false,
        "description": "badge property"
      },
      {
        "name": "icon",
        "type": "string",
        "required": false,
        "description": "icon property"
      },
      {
        "name": "active",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "Whether component is active"
      }
    ],
    "slots": [
      {
        "description": "Tab content"
      }
    ],
    "examples": [
      "<base-tab label=\"Overview\">Tab content here</base-tab>"
    ]
  },
  {
    "name": "base-tabs",
    "tagName": "base-tabs",
    "description": "Tab navigation component with horizontal and sidebar layouts",
    "category": "navigation",
    "props": [
      {
        "name": "active-tab",
        "type": "string",
        "required": false,
        "default": "",
        "description": "activeTab property"
      },
      {
        "name": "aria-label",
        "type": "string",
        "required": false,
        "default": "Dashboard navigation",
        "description": "ariaLabel property"
      },
      {
        "name": "sync-with-hash",
        "type": "boolean",
        "required": false,
        "default": true,
        "description": "syncWithHash property"
      },
      {
        "name": "variant",
        "type": "string",
        "required": false,
        "default": "sidebar",
        "description": "Visual style variant",
        "options": [
          "horizontal",
          "sidebar"
        ]
      },
      {
        "name": "force-expanded",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "forceExpanded property"
      }
    ],
    "slots": [
      {
        "description": "base-tab components"
      }
    ],
    "examples": [
      "<base-tabs><base-tab label=\"Tab 1\">Content 1</base-tab><base-tab label=\"Tab 2\">Content 2</base-tab></base-tabs>",
      "<base-tabs layout=\"sidebar\"><base-tab label=\"Settings\">Settings content</base-tab></base-tabs>"
    ]
  },
  {
    "name": "base-icon",
    "tagName": "base-icon",
    "description": "Icon display component",
    "category": "utility",
    "props": [
      {
        "name": "name",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Component name/identifier"
      },
      {
        "name": "size",
        "type": "string",
        "required": false,
        "default": "24px",
        "description": "Size of the component"
      },
      {
        "name": "color",
        "type": "string",
        "required": false,
        "default": "currentColor",
        "description": "color property"
      }
    ],
    "examples": [
      "<base-icon name=\"check\" size=\"lg\"></base-icon>"
    ]
  },
  {
    "name": "base-toast",
    "tagName": "base-toast",
    "description": "Toast notification component",
    "category": "utility",
    "props": [
      {
        "name": "variant",
        "type": "string",
        "required": false,
        "default": "default",
        "description": "Visual style variant",
        "options": [
          "default",
          "primary",
          "success",
          "warning",
          "danger",
          "info"
        ]
      },
      {
        "name": "padding",
        "type": "string",
        "required": false,
        "default": "sm",
        "description": "Internal padding size",
        "options": [
          "none",
          "sm",
          "md",
          "lg"
        ]
      },
      {
        "name": "size",
        "type": "string",
        "required": false,
        "default": "sm",
        "description": "Size of the component",
        "options": [
          "xs",
          "sm",
          "md",
          "lg"
        ]
      },
      {
        "name": "dismiss",
        "type": "string",
        "required": false,
        "default": "2s",
        "description": "dismiss property",
        "options": [
          "manual"
        ]
      },
      {
        "name": "position",
        "type": "string",
        "required": false,
        "default": "bottom-center",
        "description": "position property",
        "options": [
          "top-left",
          "top-center",
          "top-right",
          "bottom-left",
          "bottom-center",
          "bottom-right"
        ]
      }
    ],
    "examples": [
      "showToast({ message: \"Saved successfully!\", variant: \"success\" })"
    ]
  },
  {
    "name": "theme-toggle",
    "tagName": "theme-toggle",
    "description": "Light/dark theme switcher button",
    "category": "utility",
    "props": [
      {
        "name": "size",
        "type": "string",
        "required": false,
        "default": "sm",
        "description": "Size of the component",
        "options": [
          "xs",
          "sm",
          "md",
          "lg"
        ]
      },
      {
        "name": "variant",
        "type": "string",
        "required": false,
        "default": "ghost",
        "description": "Visual style variant",
        "options": [
          "ghost",
          "outline",
          "solid"
        ]
      },
      {
        "name": "themes",
        "type": "object",
        "required": true,
        "description": "themes property"
      }
    ],
    "examples": [
      "<theme-toggle></theme-toggle>"
    ]
  }
]

export const themeVariables = {
  colors: [
    '--color-primary',
    '--color-primary-hover',
    '--color-primary-light',
    '--color-secondary',
    '--color-secondary-hover',
    '--color-success',
    '--color-error',
    '--color-warning',
    '--color-info',
    '--color-bg-primary',
    '--color-bg-secondary',
    '--color-bg-muted',
    '--color-text-primary',
    '--color-text-secondary',
    '--color-text-muted',
    '--color-text-inverse',
    '--color-border',
    '--color-border-hover',
    '--color-border-focus'
  ],
  spacing: [
    '--space-1',
    '--space-2',
    '--space-3',
    '--space-4',
    '--space-5',
    '--space-6',
    '--space-8',
    '--space-10',
    '--space-12'
  ],
  typography: [
    '--font-family-sans',
    '--font-size-xs',
    '--font-size-sm',
    '--font-size-base',
    '--font-size-lg',
    '--font-size-xl',
    '--font-weight-normal',
    '--font-weight-medium',
    '--font-weight-bold'
  ],
  layout: [
    '--radius-sm',
    '--radius-md',
    '--radius-lg',
    '--radius-full',
    '--shadow-sm',
    '--shadow-md',
    '--shadow-lg'
  ]
}
